### ISSUE TITLE
Napacen prirejen element - v1692

### ISSUE THREAD

**Issue by janezicmatej** [andrejbauer/ucbenik-logika-in-mnozice#7]
Menim, da bi morala preslikava f v vrstici 1692 urejenemu paru (x,u) prirediti element "x" ne pa "a" kot napisano!

Se slikovna ponazoritev: [SLIKA](https://cdn.discordapp.com/attachments/328507038361452554/384295949897433089/unknown.png)

**Comment by MatijaSi** [comment]
Popravek sem dal v PR #8, da bo lažje popraviti napako.

Lp.

**Comment by andrejbauer** [comment]
Hvala, to je zdaj popravljeno.
